### ISSUE TITLE
Add support for HTTPS / port 443

### ISSUE THREAD

**Issue by lbausch** [CampbellSoftwareSolutions/docker-osticket#10]

**Comment by martin-css** [comment]
Sorry, been meaning to get around to replying to this.

TLS support could be added to the image. However, we would need to pick a default configuration in terms of algorithms allowed, use of DHParams, OCSP stapling etc. It will be impossible to pick a configuration that will suit everyone's needs in terms of security vs older clients they need to support and the certificates they use.

My suggestion would be to add an `/ssl` volume which would need to be populated with the SSL certificate, key and DH params file. We'd need to provide a start up script that would check for the existence of these files and configure TLS appropriately if populated.

I would suggest a good strong security configuration by default using Google DNS servers for stapling. Hence users who just want simple SSL/TLS should have a secure default. We could allow the providing of an override config file in `/ssl` to allow users with more advanced needs to still use this functionality.

Anyone got any preferences?

**Comment by lbausch** [comment]
Sounds good to me. IMO it might be sufficient to start with a strong default configuration and allow people to tweak it to their needs.

**Comment by Lubo** [comment]
Actually, adding support for HTTPS would make this image heavier than it needs to be. Just put your container behind a reverse proxy and do TLS termination there. It's very easy with, let's say, nginx.

**Comment by Jamie-** [comment]
Just giving my 2p, I agree with the above. I think that it's better to leave it as is on port 80 where it can be forwarded to another port (e.g. 8080) on the docker host. From there the user can proxy it though their (often exisiting) webserver of choice and setup SSL in there.

That's the way many like to do it, myself included.

**Comment by martin-css** [comment]
I'm happy that a consensus seems to have been reached, 1 yes & 4 nos. I'm happy to re-evaluate this in future but will close this off as *won't fix* for now.
