### ISSUE TITLE
msmtp doesn't have permission to create a log

### ISSUE THREAD

**Issue by insanity54** [CampbellSoftwareSolutions/docker-osticket#11]
I noticed that when osticket sends emails, the following error appears in `/var/log/php5-fpm.log`--

    WARNING: [pool www] child 17 said into stderr: "msmtp: cannot log to /var/log/msmtp.log: cannot open: Permission denied"

When I investigated, I found that the logfile `/var/log/msmtp.log` which is configured in [msmtp.conf](https://github.com/CampbellSoftwareSolutions/docker-osticket/blob/master/msmtp.conf) doesn't exist--

```
docker exec -it osticket /bin/bash -c 'ls -la /var/log/msmtp.log'
ls: cannot access /var/log/msmtp.log: No such file or directory
```

So it seems that the PHP user `www-data` doesn't have write access for `/var/log/`.

I'm not sure if this is the best way to fix this, but here's my proposed solution. In the Dockerfile, add these lines--

```bash
touch /var/log/msmtp.log
chown root:www-data /var/log/msmtp.log
chmod 0664 /var/log/msmtp.log
```

**Comment by martin-css** [comment]
Thanks for the report. The Dockerfile has been updated to allow `www-data` write permission to the log file.
