### ISSUE TITLE
Use sane Docker tags

### ISSUE THREAD

**Issue by Lubo** [CampbellSoftwareSolutions/docker-osticket#15]
Currently, there is only one tag in Docker registry: _latest_. Ideal situation would be having multiple tags, such as:

- 1
- 1.9
- 1.9.15
- 1.10
- ...
- latest

**Comment by martin-css** [comment]
I agree, would make sense to differentiate between the different OSTicket versions. I've put in the `1.9` and `1.10` branches which will be fixed to these versions of OSTicket. 

I'm not sure if we want to overboard with lots of image tags but if people would like specific OSTicket releases to be available then we can tag the relevant commits if necessary.
