### ISSUE TITLE
Container Restart Fails

### ISSUE THREAD

**Issue by martin-css** [CampbellSoftwareSolutions/docker-osticket#16]
As reported in pull request #14.

>My container fails to restart probably due to this line. Error log says: mkdir: can't create directory `'/run/nginx': File exists`
>Same issue will rise probably with the mkdir /var/log/php line below as well

**Comment by martin-css** [comment]
@maliayas I've applied the small fix for this. Your container should now restart successfully.

**Comment by maliayas** [comment]
Yep, now it's fine. Thanks very much for the quick action.
