### ISSUE TITLE
able to use external mysql database?

### ISSUE THREAD

**Issue by kt1024** [CampbellSoftwareSolutions/docker-osticket#2]
is it able to use external mysql database? (is this image ok/stable for production?)
thanks.

**Comment by martin-css** [comment]
I've updated the image to ensure that external MyQSL connections are supported and that the documentation reflects this. However, using a linked MySQL container is still the easiest way of using the image and will suit those that have "dockerised" their infrastructure.

I'm not aware of any issues with the image, it should be fine for production use. Please read the documentation before deploying.

If you do hit any problems, please raise an issue.
