### ISSUE TITLE
1.10 should be maintained in master

### ISSUE THREAD

**Issue by Lubo** [CampbellSoftwareSolutions/docker-osticket#20]
Since 1.10 is the latest version of osTicket, it makes sense to maintain it in master branch, rather than in a separate branch. Intentions to maintain the same code in both branches results in out-of-sync code (`latest` and `1.10` are not the same images, even though they should be) and general confusion (#18 is trying to fix a problem, which has already been solved in `1.10` branch).

**Comment by martin-css** [comment]
I agree, this is causing a bit of confusion. I've merged `1.10` into master and removed this branch. The master branch will continue to build the `latest` docker tag and will be based on the latest OSTicket major version. If this changes in the future, a `1.10` branch (or tag) will be created then for the old version.

I've removed the `1.10` tag from the docker image to avoid confusion. Unfortunately there [isn't a  way](https://github.com/docker/hub-feedback/issues/341) to build the same image automatically from the docker hub without messing around with post push hooks.

**Comment by Lubo** [comment]
You can actually do something like `1.10,latest`. It's written in the same issue you've provided link to.

**Comment by martin-css** [comment]
Only in Docker Cloud. You get an illegal character error if you try this in Docker Hub which is where the auto build is currently setup.

I'll have a look later at evaluating a move to Docker Cloud to perform the auto building.

**Comment by Lubo** [comment]
Let's move this to #21.
