### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by unibasdev** [CampbellSoftwareSolutions/docker-osticket#26]
Hi,
I'm trying to build the image using the command `docker build -t docker-osticket .` but the process fails with the following error

running: make
/bin/sh /tmp/pear/temp/pear-build-defaultuserfmhGik/apcu-5.1.8/libtool --mode=compile cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/apcu -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserfmhGik/apcu-5.1.8/include -I/tmp/pear/temp/pear-build-defaultuserfmhGik/apcu-5.1.8/main -I/tmp/pear/temp/apcu -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/apcu/apc.c -o apc.lo
mkdir .libs
 cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/apcu -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserfmhGik/apcu-5.1.8/include -I/tmp/pear/temp/pear-build-defaultuserfmhGik/apcu-5.1.8/main -I/tmp/pear/temp/apcu -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/apcu/apc.c  -fPIC -DPIC -o .libs/apc.o
In file included from /tmp/pear/temp/apcu/apc.c:40:0:
/usr/local/include/php/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
compilation terminated.
Makefile:196: recipe for target 'apc.lo' failed
make: *** [apc.lo] Error 1
ERROR: `make' failed
The command '/bin/sh -c apk add --update     wget     unzip     msmtp     ca-certificates     supervisor     nginx     libpng     c-client     openldap     libintl     libxml2     icu     openssl &&     apk add imap-dev libpng-dev curl-dev openldap-dev gettext-dev libxml2-dev icu-dev autoconf g++ make &&     docker-php-ext-install gd curl ldap mysqli sockets gettext mbstring xml intl opcache &&     docker-php-ext-configure imap --with-imap-ssl &&     docker-php-ext-install imap &&     pecl install apcu && docker-php-ext-enable apcu &&     apk del imap-dev libpng-dev curl-dev openldap-dev gettext-dev libxml2-dev icu-dev autoconf g++ make &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1

Do you have any hints of how I can solve this problem? Thanks

**Comment by martin-css** [comment]
There was an upstream change in `php:7.0-fpm-alpine` that had stopped this building as the `pcre-dev` package was removed. This has now been added back and the build should be working again.
