### ISSUE TITLE
Mail Function

### ISSUE THREAD

**Issue by judouk** [CampbellSoftwareSolutions/docker-osticket#3]
The php mail function appears not to be installed (missing sendmail). As such, I do not get notifications when new tickets are sent etc.

Could you add this to the Dockerfile?

**Comment by martin-css** [comment]
Thanks for your suggestion.

I don't want to add a SMTP service directly into the image as successfully running your own mail server is not trivial. It's relatively easy to get one up and running, it's a bit harder to get one that's secure, rejects the majority of spam and is accepted by all major ISPs. I also don't want to add a SMTP service into the image for the same reason I didn't add MySQL server, it violates the SRP for the image.

However, I agree that support for sending email should be addressed. I will see if I can add support via environmental variables for configuring PHP to use a specified SMTP server. This should allow the use of any smarthost. Alternatively, if there is already a good docker image for handling email then it could link to that - I'll have a look.

**Comment by judouk** [comment]
Hi Martin

I do agree – adding a full fledged SMTP server is not required here.
I just want to be able to receive emails from the image and, where appropriate, configure osticket to pull emails from a specified IMAP/POP3 account (for creation of new tickets).

Best Regards
Mark

**Comment by martin-css** [comment]
I've updated the image to fully support mail related functionality. All outgoing mail will be sent via a SMTP server you specify and automatic checking of incoming mail using IMAP/POP3 is also supported via a cron job.

See the README for details, this works for me when tested against an external mailbox.

**Comment by martin-css** [comment]
Closing this as the build is now available in the Docker hub. Feel free to re-open this issue if you find an issue.

**Comment by judouk** [comment]
Hi Martin

There is a problem with the install.php script.
It seems that the SMTP_TLS option is not a boolean (1/0) but a on/off statement.
As a result, all options mean TLS is enabled.

The quick fix is to update install.php (and of course, the documentation).

Best Regards
Mark

**Comment by martin-css** [comment]
The way the default value was specified for SMTP_TLS was overriding the '0' value. I've updated the script to ensure the default is only used where no value is given. Gave that a quick test and all three options (1/0/not present) should now be working as expected. The new build is now on the Docker hub.

No need for the documentation to be updated as inputs should be 0 or 1, it was just the script implementation was incorrect. As ever, feel free to re-open if you hit further issues.

**Comment by judouk** [comment]
Thanks Martin – will test this later today

**Comment by judouk** [comment]
Confirmed - now works. Thanks again
