### ISSUE TITLE
Docker hub version

### ISSUE THREAD

**Issue by PromoFaux** [CampbellSoftwareSolutions/docker-osticket#31]
Hi there, just rebuilt container to pull latest image after I noticed you'd updated the repo to be 1.10.1, however version is still showing as 1.10.

Image at docker hub appears to be 1.9, so not sure where I got 1.10 from :)

https://hub.docker.com/r/campbellsoftwaresolutions/osticket/

**Comment by PromoFaux** [comment]
Never mind, I see you've updated it now :)

**Comment by martin-css** [comment]
The docker build has got 'stuck' in Docker Hub and needed restarted. Let me know if you have problems again in the future.
