### ISSUE TITLE
File Upload won't work

### ISSUE THREAD

**Issue by feodor84** [CampbellSoftwareSolutions/docker-osticket#34]
Running osticket with a subdomain "support.mydomain.com"
Unfortunately upload won't work. 
This is the log message from osticket-error.log

`2018/02/05 06:13:21 [crit] 20#0: *13 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: 172.21.0.2, server: localhost, request: "POST /ajax.php/form/upload/41 HTTP/1.1", host: "support.mydomain.com", referrer: "https://support.mydomain.com/open.php"
`

Please tell me what I must provide in order to analyze the problem.
I assume the referrer is the problem?
 Thank you very much

**Comment by AndrewBedscastle** [comment]
Solved it:

You need to add this to the nginx.conf

``vi nginx.conf

http {
    # ...
    client_body_temp_path /tmp 1 2;
    # ...
}``
Can you please add this to the config?

**Comment by martin-css** [comment]
The issue should now be fixed in the base image. It was the permissions on `/var/tmp/nginx` that were preventing the process from reaching `/var/tmp/nginx/client_body`.
