### ISSUE TITLE
Upgrade from 1.9 to 1.10

### ISSUE THREAD

**Issue by fabriziogaliano** [CampbellSoftwareSolutions/docker-osticket#36]
Hi,

i tried to upgrade to 1.10 version but there are a lot of error message like:

tables ost_translation, ost_queue, ost_role already exists.

I tried all the combination, like so:

 - DB 1.9 dump only DATA (without schema) and after import to DB 1.10, clean installation, upgrade fail

 - DB 1.9 Upgrade directly from the new software version, upgrade fail

 - delete the tables that generate these errors and after upgrade, but, fail

any suggestions?

regards,
Fabrizio

**Comment by fabriziogaliano** [comment]
ok it's working, below the solution that worked for me:

 - docker-compose down

 - for security reason make a db dump of the current version!

 - launch these commands on DB "osticket":

DROP TABLE ost_translation, ost_role, ost_queue, ost_thread_entry, ost_thread_entry_email, ost_help_topic_form, ost_lock, ost_thread_collaborator, ost_thread_event;

ALTER TABLE ost_task DROP COLUMN lock_id, DROP COLUMN closed;

 - docker-compose up -d

 - upgrade from web interface

 - docker-compose down

 - docker-compose up -d

ENJOY IT!

**Comment by martin-css** [comment]
Thanks for posting how you successfully managed the software. Someone else might find that useful.
