### ISSUE TITLE
Conflict between 'email' and 'admin_email'

### ISSUE THREAD

**Issue by larsks** [CampbellSoftwareSolutions/docker-osticket#4]
The `install.php` script uses the `INSTALL_EMAIL` environment variable in two places (for `email` and for `admin_email`):

  'email'     => getenv("INSTALL_EMAIL") ?: 'helpdesk@example.com',
  'admin_email' => getenv("INSTALL_EMAIL")     ?: 'admin@example.com',

This results in the following error:

    Installing database. Please wait...
    Database installation failed. Errors:
      Conflicts with system email above

Caused by this in `upload/setup_hidden/inc/class.installer.php`:

        //Staff's email can't be same as system emails.
        if($vars['admin_email'] && $vars['email'] && !strcasecmp($vars['admin_email'],$vars['email']))
            $this->errors['admin_email']=__('Conflicts with system email above');

The fix is to differentiate between the email address of osticket vs. the email address of the admin user.  Consider replacing `INSTALL_FIRSTNAME`, `INSTALL_LASTNAME`, etc with `ADMIN_FIRSTNAME`, `ADMIN_LASTNAME`, `ADMIN_EMAIL`, etc...

**Comment by martin-css** [comment]
Thanks for reporting the issue. You're right, the environmental variable is incorrectly used twice for different purposes.

I've updated the image and renamed the administrator related variables to resolve. Let me know if you have any further issues.
