### ISSUE TITLE
Installer sets URL to http:///data/bin

### ISSUE THREAD

**Issue by oskapt** [CampbellSoftwareSolutions/docker-osticket#43]
Without digging too far into this, my guess is that it is because the installer is kicked off locally by `php /data/bin/install.php`. It may be taking everything before `/install.php` and deciding it's a URL. This should be easy to fix with sed to search/replace in the config after the install.

**Comment by martin-css** [comment]
The install script has now been modified to override the URL. This can be set using `INSTALL_URL`.
