### ISSUE TITLE
Upgrade Version 1.11

### ISSUE THREAD

**Issue by lucasdiedrich** [CampbellSoftwareSolutions/docker-osticket#45]
Please, upgrade to version 1.11.

Thanks

**Comment by lucamaro** [comment]
Hello,
is there a plan to implement 1.11, occifially released few days ago?

Thank you!

**Comment by martin-css** [comment]
I've updated the master branch to track v1.11 and made a new v1.10 branch to track v1.10.5. 

v1.11 will fail installation with the following error in the logs:

```
PHP Fatal error:  APCuIterator::__construct(): APC must be enabled to use APCuIterator in /data/upload/include/class.search.php on line 966
```

Unfortunately I don't have time to investigate this right now but can confirm that the `apcu` extension in installed (see line 54 in Dockerfile). If anyone would like to fix in the meantime, please feel free.

The container will start if started again as the database installation will be skipped. However, I haven't confirmed what stage this got to before failing so I wouldn't assume that the system is stable without testing further.

**Comment by lucamaro** [comment]
Hi @martin-css ,
thank you for the update. I found debugging install script that APCu is not enabled. `phpinfo` into script tells:
```
APCu Support => Disabled
[...]
apc.enable_cli => Off => Off
```

Googling around it seems the latter line to be enabled in order to have APCu working. I tried modifying the `php-osticket.ini` adding `apc.enable_cli=1` and it works.

**Comment by martin-css** [comment]
Thanks for looking into this and submitting the pull request. I can confirm the config changes to enable APCu have resolved the problem.
