### ISSUE TITLE
osTicket 1.10.5 and 1.11 have been released

### ISSUE THREAD

**Issue by kosli** [CampbellSoftwareSolutions/docker-osticket#49]
Last night the new version have been released:
 https://github.com/osTicket/osTicket/releases
Please update the dockerfile

**Comment by kosli** [comment]
see #50 for pull request.

**Comment by kosli** [comment]
unfortunately the upgrade/change won't be that easy due to #51

**Comment by martin-css** [comment]
#50 has been accepted to update to v1.10.5. Will track v1.11 in #45 to avoid duplication.
