### ISSUE TITLE
How to update this docker?

### ISSUE THREAD

**Issue by axixu** [CampbellSoftwareSolutions/docker-osticket#53]
Dear Sir,

Sorry for this question, I am new to docker, and osticket is my first docker. as osticket 1.11 released, how to update from 1.10.4 to 1.11? without losing current database and some modification i've made in upload/ folder?

**Comment by martin-css** [comment]
I'd recommend you backup your database. This runs in a separate container so you won't "lose" it however this is just a precaution in case a database upgrade failed for some reason. You can use the standard MySQL tools (e.g. in a shell session obtained from `docker exec -ti osticket_mysql bash`).

Any modifications you've made to the upload folder you'll need to copy out manually (e.g. using [docker cp](https://docs.docker.com/engine/reference/commandline/cp/)). 

You can then create a new container from the latest image, link to your DB container and run to get the latest version of OSTicket. Log into the admin panel & OSTicket should upgrade the DB as required. You would then need to copy back any relevant modifications you were preserving.

**Comment by axixu** [comment]
Hi, thank you for your guide. I just need to pull first by command `docker pull campbellsoftwaresolutions/osticket` and then create a new container, at last everything is running well.
