### ISSUE TITLE
Error occured when container started.

### ISSUE THREAD

**Issue by kuil09** [CampbellSoftwareSolutions/docker-osticket#54]
This error occured when I started osticket container.

PHP Fatal error:  APCuIterator::__construct(): APC must be enabled to use APCuIterator in /data/upload/include/class.search.php on line 966

---
It is my run script for test. What I missed?

docker run --name osticket_mysql -d -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_USER=osticket -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=osticket mysql:5

docker run --name osticket -d --link osticket_mysql:mysql -p 7777:80 campbellsoftwaresolutions/osticket

**Comment by lucamaro** [comment]
Hi @kuil09, your problem is related to #45.

**Comment by martin-css** [comment]
This is now fixed in the latest version of the image.
