### ISSUE TITLE
HTTPS (443) not enabled

### ISSUE THREAD

**Issue by mobehairy** [CampbellSoftwareSolutions/docker-osticket#55]
need to enable HTTPS (443) on the app

**Comment by jortkoopmans** [comment]
Generally for container based apps, the TLS termination is done with a different container. What is your exact need for having this capability on the app itself?
Have you considered for example Traefik? (https://docs.traefik.io/)

**Comment by mobehairy** [comment]
i will post the edits on nginx.conf which includes HTTP and HTTPS  and redirection from HTTP to HTTPS for anyone needs it.

**Comment by mobehairy** [comment]
user  www-data;
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 2;
    client_max_body_size 100m;

    server {
        listen 80;
        server_name helpdesk.example.com;
	return 301 https://helpdesk.example.com;

        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;

        root /data/upload;
        index index.html index.htm index.php;

        access_log /var/log/nginx/osticket-access.log;
        error_log  /var/log/nginx/osticket-error.log error;

        charset utf-8;

        set $path_info "";

        location ~ /include {
            deny all;
            return 403;
        }

        if ($request_uri ~ "^/api(/[^\?]+)") {
            set $path_info $1;
        }

        location /api {
            try_files $uri $uri/ /api/http.php?$query_string;
        }

        if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }

        if ($request_uri ~ "^/ajax.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/ajax.php/.*$ {
            try_files $uri $uri/ /ajax.php?$query_string;
        }

        location / {
             try_files $uri $uri/ index.php;
        }

        location = /favicon.ico { log_not_found off; access_log off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        # Deny .htaccess file access
        location ~ /\.ht {
            deny all;
        }

        location ~ \.php$ {
             try_files      $uri = 404;
             fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
             include        fastcgi_params;
             fastcgi_index  index.php;
             fastcgi_param  LARA_ENV local; # Environment variable for Laravel
             fastcgi_param  PATH_INFO   $path_info;
             fastcgi_pass   127.0.0.1:9000;
        }
    }
    server {

	listen   443;
	server_name helpdesk.example.com;
	ssl    on;
	ssl_certificate    /data/upload/include/plugins/sum.crt;
	ssl_certificate_key    /data/upload/include/plugins/sum.key;

	root /data/upload;
	index index.html index.htm index.php;

	access_log /var/log/nginx/localhost_ssl.access.log;
	error_log /var/log/nginx/localhost_ssl.error.log error;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
		
        charset utf-8;

        set $path_info "";

        location ~ /include {
            deny all;
            return 403;
        }

        if ($request_uri ~ "^/api(/[^\?]+)") {
            set $path_info $1;
        }

        location /api {
            try_files $uri $uri/ /api/http.php?$query_string;
        }

        if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }

        if ($request_uri ~ "^/ajax.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/ajax.php/.*$ {
            try_files $uri $uri/ /ajax.php?$query_string;
        }

        location / {
             try_files $uri $uri/ index.php;
        }

        location = /favicon.ico { log_not_found off; access_log off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        # Deny .htaccess file access
        location ~ /\.ht {
            deny all;
        }

        location ~ \.php$ {
             try_files      $uri = 404;
             fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
             include        fastcgi_params;
             fastcgi_index  index.php;
             fastcgi_param  LARA_ENV local; # Environment variable for Laravel
             fastcgi_param  PATH_INFO   $path_info;
             fastcgi_pass   127.0.0.1:9000;
        }
}
}

daemon off;

**Comment by martin-css** [comment]
Thanks for the contribution. I'm sure other will find the config useful.

However, one of the reasons that TLS is often left out of base images is that this can be configured in many different ways depending on clients you need to support etc. For example above, there is no OSCP stapling (`ssl_stapling`), no preferred protocol (`ssl_protocols`) & cipher (`ssl_ciphers`) lists, no Diffie-Heleman parameters (`ssl_dhparam`).

You can open yourself up to various attacks if your TLS configuration is not secure, ideally this should be tested with a tool - I find [SSL Labs](https://www.ssllabs.com/) to be very useful.

As such, containers tend to be reverse proxied behind other containers designed for TLS termination. These can also offer useful extra functionality around monitoring, dynamic service switching etc.

As such, I'm not intending on adding TLS config to the nginx config as we already discussed this in #10. If there is a consensus that this would be useful then this could change in the future.
