### ISSUE TITLE
PHP 7.0.x EOL: Update Dockerfile?

### ISSUE THREAD

**Issue by gbxnet** [CampbellSoftwareSolutions/docker-osticket#57]
PHP 7.0.x has EOL since Jan 2019. Would be nice if you could update your Dockerfile with php 7.3.x (or any other supported version).

**Comment by gbxnet** [comment]
Info that I've got from osticket support. Apparently we can use it with php <= 7.2.X

> You can actually use up to PHP 7.2 with the latest version of osTicket. In the event you run into any issues please let us know as there may be pull requests on our Github page since our developers are actively working to fix bugs as they are reported.
> 
> Thanks again and please let us know if you have any other questions. 
> 
> -- 
> Bianca Malone
> Resident Weather Girl 
> 
> Enhancesoft
> parent company of
> osTicket & SupportSystem

**Comment by martin-css** [comment]
I've updated to PHP 7.2 in the base image since 7 is now end of life. Hopefully all should be fine but anyone who has issues should report these to OSTicket so they can get any unexpected compatibility issues resolved.
