### ISSUE TITLE
Connecting to external MySQL with different port

### ISSUE THREAD

**Issue by Pyreweb** [CampbellSoftwareSolutions/docker-osticket#59]
Hi,

I've tried to start the container with our external MySQL instance, but it stops at `Waiting for database TCP connection to become available...`
I've checked into your files, it seems that the port is hardcoded to 3306 in files/data/bin/install.php, line 132. Ours is 32768 and can't be changed.
Can you add an ENV var to set port, a `MYSQL_PORT` maybe ?

**Comment by martin-css** [comment]
Can now specify `MYSQL_PORT` with the port you'd like to connect to if using an externally MySQL server connection

**Comment by Pyreweb** [comment]
Nice, it works for us now 😄 
Thanks a lot !
