### ISSUE TITLE
Are there any plans to update it to OsTicket 1.12

### ISSUE THREAD

**Issue by parijathakumar** [CampbellSoftwareSolutions/docker-osticket#61]
As OsTicket 1.12 is released now, are there any plans to update the image ?

**Comment by axixu** [comment]
up, please update to 1.12.

**Comment by rogedelgado** [comment]
Yes please, update to 1.12. That would be great!

**Comment by martin-css** [comment]
I've updated the image to v1.12 and added a `1.12` tag to the Docker image (which is now `latest` as well). v1.11 will continue on the `1.11` image tag.

I've confirmed OsTicker installs & starts successfully but not really tested the new image any further. If anyone encounters any issues with the image configuration that needs updated then let me know.
