### ISSUE TITLE
Timezone issue, causing lock issues

### ISSUE THREAD

**Issue by libussa** [CampbellSoftwareSolutions/docker-osticket#66]
Hello,
I migrated to this version from a hosted osticket. I'm using an external Mysql database.
Everything is set to UTC: php, system, mysql.
But when I try to answer a ticket or make a note, I get "This action requires a lock. Please try again!"

When I change the Timezone to Paris, the time is wrong everywhere (stays UTC).

Any leads on how to solve this?

**Comment by fkrauthan** [comment]
@libussa I have the same issue how where you able to resolve it?
