### ISSUE TITLE
Email fetching not working after restart

### ISSUE THREAD

**Issue by kosli** [CampbellSoftwareSolutions/docker-osticket#8]
I had this issue already with the 1.9.12 version and thought it would be fixed in 1.9.14, so I am opening now an issue. 

I have set up one "email" which fetches an IMAP account. This works fine, but when I stop and start the container again, it stops working. The strange thing is that i receive a "Mail Fetch Failure Alert" mail (Error: IMAP Authentication cancelled) which is send with the credentials of this fetching account that doesn't work. After entering and saving the password of that account, the fetching works again. I would have thought that the password is stored in the DB and so there is no influence on the stopping/destroying the container, as long as the mysql server is running? 

Has anybody else run into this issue?

**Comment by martin-css** [comment]
Are you setting the `INSTALL_SECRET` environmental variable?

OSTicket stores an encrypted version of the IMAP account password in the database. This is the `SECRET_SALT` variable in the source code. The value to use is declared and read in from the settings file.

This image will automatically generate a weak random value when you start a container if this is not specified. However, if you start a new image, a new value will be generated and this will not match the previous value, hence decryption of the IMAP password would fail. 

If you set `INSTALL_SECRET` to some random value with sufficient entropy then this should prevent this problem.

**Comment by martin-css** [comment]
Closed due to no response. Feel free to re-open if the issue isn't resolved.

**Comment by kosli** [comment]
@martin-css thank you very much! it seems that i missed that part in the installation instructions. sorry for bothering. and sorry for the slow reply, i was on holiday.

**Comment by martin-css** [comment]
No problem, glad the problem is fixed.
