### ISSUE TITLE
12 factor app / 1 process /container

### ISSUE THREAD

**Issue by pierreozoux** [CampbellSoftwareSolutions/docker-osticket#9]
Hi! and thanks for your work!

Do you plan to have one process per container. And transform this image into a pure fpm one?

Let me know!

Pierre

**Comment by martin-css** [comment]
It's not something I have strong feelings on either way. Obviously a container with php5-fpm and no supervisord would be more aligned with the *Docker way* of one process per container. 

However, one of the benefits of this image is that it's very easy to get a copy of OSTicket up and running without worrying about installing or configuring software, including nginx. Particularly as some of the rules required for reverse proxying OSTicket can be convoluted. Hence why I'd taken the pragmatic approach to replicate the original image and keep nginx and php5-fpm together.

 Overall, I agree that removing nginx is probably better. This would allow users to specify their own web front end and configure this as necessary (e.g. TLS, caching etc). However, if we go down this road, I think we need to make a docker-compose script (or similar alternative) to make getting up and running as simple as possible, ideally a copy & paste one liner. Ideally, using the existing `nginx` docker image without needing to create a derivative.

I'll leave this issue open for a little while. If anyone else has any comments, please feel free to contribute. I'll make a decision after seeing what the general consensus is.

**Comment by pierreozoux** [comment]
https://github.com/indiehosters/docker-osticket

https://github.com/indiehosters/osticket

Let me know if we can work together on this and also:
https://github.com/osTicket/osTicket/issues/3392

**Comment by martin-css** [comment]
I've not had any other comments on a preferred approach. Given the other image exists which is perhaps more the *Docker way*, users can choose which image they'd like to use. Hence it probably makes sense to keep this as a more pragmatic easy to use way of getting OSTicket up and running.

I'm closing this just now but anyone with any comments can re-open the issue.
