### ISSUE TITLE
setting up smtp woes

### ISSUE THREAD

**Issue by eddyizm** [CampbellSoftwareSolutions/docker-osticket#90]
I'm having a hell of a time setting up the smtp mail. 

I tried setting up the settings in the app (successfully authenticates but fails to test send) and I tried setting the environmental variables with the smtp configuration, no luck.
Been scouring the osticket docs and coming back here in the closed issues but I'm guessing this is not getting updated anymore? 

Any help appreciated.

**Comment by bobweston** [comment]
I'm not working on this project. So I can't help there. But you ought to be able to pass it the proper parameters in the `docker run` command.

`-e SMTP_HOSTS=smtp-xxx.xxx.com -e SMTP_PORT=25 -e SMTP_FROM=xxxxxx@xxx.com -e SMTP_TLS=0 `

There may be others for your specific environment. But this works for me

**Comment by eddyizm** [comment]
Thanks for the response @bobweston I had tried that unsuccessfully but it may have been a gmail thing. I have since moved on from this client project.
